### ISSUE TITLE
line item creation

### ISSUE THREAD

**Issue by seyfullah642** [googleads/googleads-displayvideo-examples#2] opened 2021-04-09 16:34 UTC
Hello,

I am using the example dictionary you have in your create_line_item.py script and I am getting the http 400 error below. 

```
line_items_obj = {
        'insertionOrderId': '19420041',
        'displayName': 'Test Number 1',
        'lineItemType': 'LINE_ITEM_TYPE_DISPLAY_DEFAULT',
        'entityStatus': 'ENTITY_STATUS_DRAFT',
        'flight': {
            'flightDateType': 'LINE_ITEM_FLIGHT_DATE_TYPE_INHERITED'
        },
        'budget': {
            'budgetAllocationType': 'LINE_ITEM_BUDGET_ALLOCATION_TYPE_FIXED'
        },
        'pacing': {
            'pacingPeriod': 'PACING_PERIOD_DAILY',
            'pacingType': 'PACING_TYPE_EVEN',
            'dailyMaxMicros': 10000
        },
        'frequencyCap': {
            'timeUnit': 'TIME_UNIT_DAYS',
            'timeUnitCount': 1,
            'maxImpressions': 10
        },
        'partnerRevenueModel': {
            'markupType': 'PARTNER_REVENUE_MODEL_MARKUP_TYPE_CPM',
            'markupAmount': 10
        },
        'bidStrategy': {
            'fixedBid': {
                'bidAmountMicros': 100000
            }
        }
    }
```

`<HttpError 400 when requesting https://displayvideo.googleapis.com/v1/advertisers/679665046/lineItems?alt=json returned "The revenue model cost amount cannot be too small or too large.". Details: "The revenue model cost amount cannot be too small or too large.">`

I was successful in creating a campaign and insertion order in a sandbox environment I have in DV360. Not sure how to troubleshoot the error I provided.

Thanks,
Sinan

**Comment by tmulchay** [comment] 2021-04-09 21:30
Hi Sinan,

I believe that this error is being caused by the `markupAmount` value of 10. Try changing the value to 10000, which I believe is the lowest allowable amount, equating to $0.01 in the UI. This will be fixed in the existing examples shortly.

Thank you,
Trevor Mulchay, DV360 API Team

**Comment by seyfullah642** [comment] 2021-04-12 14:41
Hey Trevor,

Thanks for the quick response. That did work :)

Kind Regards,
Sinan

**Closed** 2021-04-12 14:41 UTC
